server:
  port: 8090
  
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mydb_2023_03_18?useUnicode=true&characterEncoding=UTF-8&autoconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    
  thymeleaf:
    cache: false
    encoding: UTF-8
#    mode: HTML
    prefix: classpath:/templates/
    suffix: .jsp
    
mybatis:
  type-aliases-package: com.example.demo.pojo #com.example.demo.mapper
  mapper-locations:
  - classpath:/mappers/*.xml